'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mod = require('../handler.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'create' });

describe('create', () => {
    before((done) => {
        //  lambdaWrapper.init(liveFunction); // Run the deployed lambda
        done();
    });

    it('implement tests here', () => {
        return wrapped.run({}).then((response) => {
            debugger
            expect(response).to.not.be.empty;
        });
    });
});
